### ISSUE TITLE
PokerTracker 4 Not Importing Hands

### ISSUE THREAD

**Issue by bclayman** [bclayman/HHConverter2#1]
When I load this hand into PokerTracker 4:

PokerStars Game #45715290124: Tournament #284245586, $2.00+$0.20 USD Hold'em No Limit - Level XIX (50/100) - 2010/06/19 16:32:38 WET [2010/06/19 11:32:38 ET]
Table '284245586 5' 9-max Seat #7 is the button
Seat 2: test4 (20000 in chips)
Seat 7: test5 (20000 in chips)
test5 posts: small blind 50
test4 posts: big blind 100
**\* HOLE CARDS ***
Dealt to test4 [7d 3s]
Dealt to test5 [3d Kd]
test5: raises 250 to 300
test4: folds
**\* SHOW DOWN ***
test4: shows [7d 3s]()
test5: shows [3d Kd]()
test5 collected 100 from pot

I get this error: Warning: PokerStars: Big Blind not posted in hand#45715290124 (Line #16)

When I modify the end of the hand, by appending:

**\* SUMMARY ***
Total pot 100 | Rake 0
Seat 2: test4 (big blind) folded before the Flop
Seat 7: test5 (button) collected (100)

I get the same error on Line #19.

**Comment by kissgyorgy** [comment]
You should put colon after the name, not after the post words. Also maybe (small blind) is missing from summary. Here is a good format you can import:
[goodformat.txt](https://github.com/pokerregion/HHConverter2/files/7314/goodformat.txt)
